language: android
services:
  - docker
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
 global:
    # Global variables to get things easier to change
    - ANDROID_API_LEVEL_TARGET=28
    - ANDROID_API_LEVEL_EMULATOR=21
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - CMAKE_VERSION=3.6.4111459
    - LLDB_VERSION=3.0

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PATH="$PWD/build:$PATH"
  - conda info -a
  - source activate base
  - conda install -y -c conda-forge meson ninja
  # Special packages for the project
  - echo "y" | sdkmanager "ndk-bundle"
  - echo "y" | sdkmanager "cmake;$CMAKE_VERSION"
  - echo "y" | sdkmanager "lldb;$LLDB_VERSION"

android:
  components:
  # Tools Version of the project
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL_EMULATOR
  - android-$ANDROID_API_LEVEL_TARGET
  # More components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  # Image for the emulator
  - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL_EMULATOR

before_script:
  - bash before_operations.sh

script:
  - bash update_fakeinput_jar_asset.sh
  - bash build_operations.sh

deploy:
  provider: releases
  api_key:
    secure: ZiWMeEJKwD4WHsT5d4qUy0EnX9idTpKDqEtOdqJ8+tHbjQTeNj9lANrvNJsnKpNZIFro1E6TjsC/HHlHe0XLwHop0AAe37E9iPjoWqy5DnTp1JvUStFMVNfIkLXNcUsCXPWc0XkMqA/S1Pz/6oEPvLa5LvkFvx3CKvoQt0Diadj50FQG8Dn0IA0y+zKmPoY96CdgFZdTB+xBsp8TEVpzacYh2TeNbNvd0ZCDMqjfORJHHsyDXTIYlINNRd9XI+ugNQfYVoaf8IYjAEfj9oS2SZ9u3CYG+y/brvJla3WmJV91F3E4yKVo2Yw6bXoEJJdHxdJVj8ODOUmpyMdB0RbTMDP2+UEVVTAE6ZPYQ/GyDhB4gkgTVgypd2C/ZV6IPAtLdw9qX6AojIjnUzHLXqK9gPSgMuRvcvxCdgXpQnRrX1oi+9MXTfBCy+BJL0vFbAwynSfKVdaMOUOAygH7m0Fpy2kVfXgT6CwcTHYDZqnTPYRD2dKF3w/wI+SD+nZhMifRXXj9MnypYm+/id3k816RmSBgOum9Ebotw7jJiriILa/aXxIUajxF7jbQK4wfLWnmtIZZ4mYvemM71f1+DjY+crJ4MFg9RDTOKuDWfcfKRomyEqqUv5PVPqL03aA2hSniowv6sYRrC5ySaOVUOCNGGf2Ks+PF1PYBZpJ2byeNp8U=
  file: "amos-tub-ws18-proj1/*"
  skip_cleanup: true
  on:
    tags: true
