language: android
services:
  - docker
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"
env:
  global:
    - ANDROID_API_LEVEL_TARGET=28
    - ANDROID_API_LEVEL_EMULATOR=21
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - CMAKE_VERSION=3.6.4111459
    - LLDB_VERSION=3.0
    - secure: r5z0kVZpHO+PTxqzY9LCE3X9Ov6uDTh5GEy+6afENbETsZtw8VocsllXdMqzBF2geJNQZw9fvdWmGLWN71k33i1Jx4vhzdIB59SFpZiWQvg8YztUgCqcfkp32a42Cg7Vv+TAdZDH5zinfhx0iGsHB81HcMCyssgoBoZVvZ34iyNeyV1cAHiJe92yBY1ocWKun9ob1x4WDRxhLlRvp9Vdwr4haqzXBIPFJOiG6hCzTlBrKQoUukMvpekBNfpx1QxuBZWQgANm8DuSRDQWW0Ff4sh0mlLh0OtpGT4zxrCof+jxZ87X713pfGcr1YBC1IeOKh4InOTtCL2aasuHk6Apwog399C0QrR0MBObH+VZFMfkGx7kT2CPyAVcg7lYp5Q/1x+RDF1bXOkxYpLD6wAALKcc+krqtQNA2/YFsZUM9u2rTJuoo0dOhhjzkDgCxx+1e86Lx7nhWL//B+djGAXzecYoBc1OwAatMWQVBZCUTRAQiNsyOS3I2X3XBjGgjHcrFdk5NJ6SZXvZ7zOTzEWlvFWaSnoB8h5ao2/AAYIzgG4R1yDmjsUlIwx7Sg7OoVaG42ey9YykM0Y/ueA07Ct7g96RapY/IJ6aow2gF3cpiMQQjiY1IvBnpToj4lhWhuJakl4JhAH+wAP1TBvnmXJOc79Q3zIeKkpn8BZIG/11vZ0=
    - secure: T5eF+B+09qF61pHoqJkfZJc+vYdp6IbDEgjrNldDal/Jujbnr+2YmlRdLb8/ZZr/K+HQogruDHXgtgYYLcnBOPiDL5Cj6LJ9ORO6OvP5GDVc5X4EDR8srfeOvE5+qGvhCgvLQxmnWAmJZDYZJPecJDPaF82aBZdzaC9R0dZVKPp3HOmqmlb4ZkX5wsBHq7xjeckXVwj1RjB8udMG2FVn6DXMGwcFjYc1W9JOJcbwtAqvtHNlXONaYD19P2T29JmtKgpNv/hVySSyGESw2r4+u2gaf++RM1UxvgaRqswXLunjNC7rOzDS7QOuFafpPQrZfKnbfMC6ElY2hCSzRGgZ4TRHp2BYs+CuVw0wm6x+SX17Z+1MCd6fFvGErM/AETJNaVXkChzQ/QcUfQhfV63RTi470Ve6yMs1zWKIAuhAP9XDMoPVY0OmvcZI6odbhE5MEQjGnlxUCr8DHqv7E00MoIx8tcaAqmQR1oy0YZ//NzKysJ/GKesCdcUsKiSrKV6KGnyAqTa6NiMKyOT6aPXxh9k3ZNENdm7N2Odfuy6el/6wrJIgM5CRUFiSshkIhAPw4jfldXSiC8aiFEJGeCouv8L49i15LJ/HvvY0ZMt2yfpXgK2FN6nWsgZshMMdjpLLfWZMO+1Hmiklp4h0HAOU7G+S9obNECLdjOivSmZh/nw=

before_install:
  - openssl aes-256-cbc -K $encrypted_cf4480f630ba_key -iv $encrypted_cf4480f630ba_iv -in flyinn-keystore.jks.enc -out flyinn-keystore.jks -d

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export PATH="$PWD/build:$PATH"
  - conda info -a
  - source activate base
  - conda install -y -c conda-forge meson ninja
  - echo "y" | sdkmanager "ndk-bundle"
  - echo "y" | sdkmanager "cmake;$CMAKE_VERSION"
  - echo "y" | sdkmanager "lldb;$LLDB_VERSION"

android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL_EMULATOR
  - android-$ANDROID_API_LEVEL_TARGET
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL_EMULATOR

before_script:
  - bash before_operations.sh

script:
  - bash update_fakeinput_jar_asset.sh
  - bash build_operations.sh

before_deploy:
  - cp $TRAVIS_BUILD_DIR/.keystore $HOME

  - cd app/build/outputs/apk/release
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/flyinn-keystore.jks
    -storepass $storepass -keypass $keypass app-release-unsigned.apk flyinn-keystore
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk flyinn-client.apk"

  - cd server/build/outputs/apk/release
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/flyinn-keystore.jks
    -storepass $storepass -keypass $keypass server-release-unsigned.apk flyinn-keystore
  - jarsigner -verify server-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 server-release-unsigned.apk flyinn-server.apk"

deploy:
  provider: releases
  api_key:
    secure: ZiWMeEJKwD4WHsT5d4qUy0EnX9idTpKDqEtOdqJ8+tHbjQTeNj9lANrvNJsnKpNZIFro1E6TjsC/HHlHe0XLwHop0AAe37E9iPjoWqy5DnTp1JvUStFMVNfIkLXNcUsCXPWc0XkMqA/S1Pz/6oEPvLa5LvkFvx3CKvoQt0Diadj50FQG8Dn0IA0y+zKmPoY96CdgFZdTB+xBsp8TEVpzacYh2TeNbNvd0ZCDMqjfORJHHsyDXTIYlINNRd9XI+ugNQfYVoaf8IYjAEfj9oS2SZ9u3CYG+y/brvJla3WmJV91F3E4yKVo2Yw6bXoEJJdHxdJVj8ODOUmpyMdB0RbTMDP2+UEVVTAE6ZPYQ/GyDhB4gkgTVgypd2C/ZV6IPAtLdw9qX6AojIjnUzHLXqK9gPSgMuRvcvxCdgXpQnRrX1oi+9MXTfBCy+BJL0vFbAwynSfKVdaMOUOAygH7m0Fpy2kVfXgT6CwcTHYDZqnTPYRD2dKF3w/wI+SD+nZhMifRXXj9MnypYm+/id3k816RmSBgOum9Ebotw7jJiriILa/aXxIUajxF7jbQK4wfLWnmtIZZ4mYvemM71f1+DjY+crJ4MFg9RDTOKuDWfcfKRomyEqqUv5PVPqL03aA2hSniowv6sYRrC5ySaOVUOCNGGf2Ks+PF1PYBZpJ2byeNp8U=
  file:
    - flyinn-client.apk
    - flyinn-server.apk
  skip_cleanup: true
  on:
    repo: amos-flyinn/amos-tub-ws18-proj1
    tags: true
